package com.example.bch__8_11.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.bch__8_11.bean.ProductsBean;

import com.example.bch__8_11.greendao.ProductsBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig productsBeanDaoConfig;

    private final ProductsBeanDao productsBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productsBeanDaoConfig = daoConfigMap.get(ProductsBeanDao.class).clone();
        productsBeanDaoConfig.initIdentityScope(type);

        productsBeanDao = new ProductsBeanDao(productsBeanDaoConfig, this);

        registerDao(ProductsBean.class, productsBeanDao);
    }
    
    public void clear() {
        productsBeanDaoConfig.clearIdentityScope();
    }

    public ProductsBeanDao getProductsBeanDao() {
        return productsBeanDao;
    }

}
